### ISSUE TITLE
integrate in laravel website

### ISSUE THREAD

**Issue by amirgee007** [oleksandr-torosh/demio-php-sdk#6]
hi, i want to integrate into my laravel project and my ideas is whenever the user will register it automatically add that email in the Demio and give me url to see the webinar without any new registration process.

thank

**Comment by alexander-torosh** [comment]
Hi, @amirgee007 you can review the example here https://github.com/meetdemio/demio-php-sdk/blob/master/examples/register.php
This code registers new registrant to your Event.
Also, it works with Event registration link as parameter https://github.com/meetdemio/demio-php-sdk#register-via-registration-page-link
